### ISSUE TITLE
Converge

### ISSUE THREAD

**Issue by Cjwer** [fulcrum-zou/VRP-GCN-NPEC#1]
Hello, I used your code to apply to VRP problem. During training, it seems that the performance of the model does not converge. I would like to ask if you have encountered such a situation?

**Comment by fulcrum-zou** [comment]
Hi, thank you for asking. I did have the same problem last year. But I doubled checked my code then. I was pretty sure it has strictly followed all the equations in the paper. However, I'm not very familiar with reinforcement learning. I doubted that I might have misunderstood some steps with regard to RL. This was just one of my assignments last year, so I didn't dive deeper in this problem. You can check `environment.py` if you want to.
